# Generated by Django 5.1.6 on 2025-02-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_request', models.TextField()),
                ('generated_query', models.TextField()),
                ('query_result', models.TextField()),
                ('raw_data_excerpt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
